#!/bin/bash
# shellcheck disable=SC2016
# SC2016 Expressions don't expand in single quotes ('```')

##### license LPRAB/WTFPL
#  auteur: sdeb
#    contributeurs: kyodev
#####

version=1.6.3
script="nstest"
date="05/06/2018"
#~ contact="irc:freenode.net##sdeb"

if ! command -v sort > /dev/null; then
	echo -e "'sort' not found, install coreutils if you want a sorted report\\n"
fi
if command -v dig > /dev/null; then
	dig=dig
elif command -v drill > /dev/null; then
	dig=drill
	echo -e "'dill' is terribly slower (no management timeout), for frequent use, install dig (dnsutils) \\n"
else
	echo "dig (and drill) not found,  install it with dnsutils"
	exit 1
fi

	# assign ${nameservers[@]} ${dns[@]} $domains_qty, require $testarray
assign_variables(){		# 01/06/2018
			# NO SPACE in service name, if not `sort` will fail
	dns4=(
		'176.103.130.130 # adguard'
		'23.253.163.53 # alternate_dns'
		'185.228.168.168 # cleanbrowsing'
		'1.1.1.1 # cloudflare'
		'8.26.56.26 # comodo'
		'84.200.69.80 # dns_watch'
		'216.146.35.35 # dyn_oracle'
		'37.235.1.174 # freedns'
		'80.80.80.80 # freenom'
		'8.8.8.8 # google'
		'209.244.0.3 # level3'
		'156.154.70.1 # neustar'
		'199.85.126.10 # norton'
		'208.67.222.222 # opendns'
		#~ '185.121.177.177 # openNic_anycast'	
		#~ '169.239.202.202 # openNic_anycast'	
		'9.9.9.9 # quad9'
		'91.239.100.100 # uncensoredDNS'
		'64.6.64.6 # verisign '
		'77.88.8.8 # yandex'
			#~ fail 06/2018
		#~ '179.43.139.226 # Fourth_Estate_Zurich'
		#~ '81.218.119.11 # greenTeamDns'
		#~ '185.121.177.177 # openNic_anycast'	
		#~ '208.76.50.50 # smartViper'
	)
	dns6=(
		'2a00:5a60::ad1:0ff # adguard'
		#~ '2606:4700:4700::1111 # cloudflare'
		'2606:4700:4700::1001 # cloudflare'
		'2001:1608:10:25::1c04:b12f # dns_watch'
		'2001:4860:4860::8888 # google'
		#~ '2a05:dfc7:5::53 # openNic_anycast'
		#~ '2a05:dfc7:5::5353 # openNic_anycast'
		'2610:a1:1018::1 # neustar'
		'2620:fe::fe # quad9'
		'2001:67c:28a4:: # uncensoredDNS'
		'2620:74:1b::1:1 # verisign '
		'2a02:6b8::feed:0ff # yandex'
			#~ fail 06/2018
		#~ '2a0d:2a00:1 # cleanbrowsing'
		#~ '22620:0:ccc::2 # opendns'
	)

	case "$testsarray" in
		alt )
			domains_test=(
				whois.biz
				pik.bzh
				www.coop
				lafibre.info
				github.io
				bmwgroup.jobs
				dotmobi.mobi
				do.tel
				france.tv
				gen.xyz
			) ;;
		atld )
			domains_test=(
				register.bbs
				opennic.chan
				opennic.cyb
				nic.fur
				rojaciwan.ku
				register.neo
				reg.null
				opennic.oz
				uptime.party 
				vtje.ti
			) ;;
		base )
			domains_test=(
				debian.org
				eurid.eu
				free.fr
				google.com 
				info.info
				kernel.org
				be.libre
				ovh.net
				packager.io
				transfer.sh
			) ;;
		easy )
			domains_test=(
				amazon.com
				facebook.com
				github.com
				gmail.com
				google.com
				reddit.com
				twitter.com
				whatsapp.com
				wikipedia.org
				youtube.com
			) ;;
	esac
	domains_qty=${#domains_test[@]}
}

	# détermination dirname et basename avec suivi lien éventuel, assigne $dirscript & $basescript
f__basedirname(){		# 28/04/2018

	dirscript=$( readlink -f "$0" )		# /path/from/root/scriptname (absolute path)
	# shellcheck disable=SC2034
	basescript=${dirscript##*/}			# scriptname
	dirscript=${dirscript%/*}			# /path/from/root/
}

	# $1 message to display
f__die(){		# 05/06/2018

	echo -e "\\n  Fatal: $1"
	exit 1
}

	# display the ip protocol of the network layer: -4|-6|-46
f_ip_proto_detect(){		# 01/06/2018
	local protoPossible noif if inet z protocol

	protoPossible=$( LC_ALL=C ip -o a  )
	# shellcheck disable=SC2034
	while read -r noif if inet z; do
		if [[ "$inet" == "inet" && "$noif" != "lo" ]]; then
			protocol+='-4'
		elif [[ "$inet" == "inet6" && "$noif" != "lo" ]]; then
			protocol+='-6'
		fi
	done <<< "$protoPossible"
	case "$protocol" in -4-6* | -6-4* ) protocol="-46" ;; esac
	echo "$protocol"
}

	# $1 temps en secondes, affiche conversion en jours, h, mn, s
f__sec2day(){		# 05/05/2018
	local j h mn sec display

	  j=$(( $1 / (24*3600) ))
	  h=$(( ($1 % (24*3600)) / 3600 ))
	 mn=$(( (($1 % (24*3600)) % 3600) / 60 ))
	sec=$(( (($1 % (24*3600)) % 3600) % 60 ))
	(( j != 0)) && display+="$j jours "
	(( h != 0)) && display+="$h h "
	(( mn != 0)) && display+="$mn mn "
	(( sec != 0)) && display+="$sec s "
	echo "${display% }"
}

	# $1: ip to analyze, display protocol -4|-6|0
f_ip_protocol(){		# 24/05/2018
	reg="(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])"  
	regex="^$reg\\.$reg\\.$reg\\.$reg$"
	if [[ "$1" =~ $regex ]]; then
		echo -4
		return 0
	fi
	regex="^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$"
	if [[ "$1" =~ $regex ]]; then
		echo -6
		return 0
	else 
		echo 0
		return 1
	fi
}

	# getTime : start count
	# getTime end : comptage fin, calcul fin - départ, affichage différence en ms
	# getTime end:sec : idem sauf affichage différence en s
	# getTime end:auto : idem sauf affichage différence en j, h, mn, s si diff > 10s
	# getTime affichage date en ms, sans unité, pour traitement externe à la fonction
	# lien utile: https://www.admin-linux.fr/conversion-des-timestamps-dates-au-format-unix-en-bash/
	# declare -g gTime
getTime(){	# 25/05/2018
	local date sec ms time2
	declare -g gTime
	date=$( date +%s.%N )	# s.ns timestamp.ns
	sec=${date%\.*}		# s
	ms=${date#*\.}		# ns
	ms=${ms::-6}		# ms
	if [[ "$*" =~ "end" ]]; then
		if [[ "$*" =~ "sec" ]]; then
			time2=$(( $sec$ms-gTime ))
			echo "${time2::-3}.${time2: -3} s"		# sec avec virgule
		elif [[ "$*" =~ "auto" ]] && (( ( $sec$ms-gTime ) >= 10000 )); then
			f__sec2day "$(( sec-${gTime::-3} ))"
		else
			echo "$(( $sec$ms-gTime )) ms"
		fi
	else
		gTime="$sec$ms"					# calcul sur ms
	fi
}

	# assign ${nameservers4[@]}, ${nameservers6[@]}, [$1=file where are name's server], by default, resolv.conf is readed
readingFileNs(){		# 01/06/2018
	local a ip ns 

	unset nameservers
	if [ "$1" ]; then
		# shellcheck disable=SC2034
		file="$1"
		while read -r ip ns; do 
			if [[ ! "$ip" =~ ^[[:blank:]]?# ]]; then
				[ "$ns" ] && title="$ns" || title="# file"
				if (( $( f_ip_protocol "$ip" ) == -4 )); then
					nameservers4+=( "$ip $title" )
				else
					nameservers6+=( "$ip $title" )
				fi
			fi
		done < "$1"
	else
		while read -r a ip ns; do 
			if [ "$a" == "nameserver" ]; then
				[ "$ns" ] && title="$ns" || title="# resolv"
				if (( $( f_ip_protocol "$ip" ) == -4 )); then
					nameservers4+=( "$ip $title" )
				else
					nameservers6+=( "$ip $title" )
				fi
			fi
		done < /etc/resolv.conf
	fi
}

	# $1 téléchargement déjà fait, assigne $online_version
script_get_version(){		# 01/06/2018
	local temp  

	if [ "$1" ]; then
		temp="$1"		# version fichier
	else
		! temp=$( curl --silent --show-error "$url_script" ) && f__die "error getting script online version"
	fi
	temp=${temp#*version=}
	read -r online_version <<< "$temp"
	[[ "${online_version:0:1}" =~ [0-9] ]] || online_version="${RED}n/a"
	[ "$1" ] && return 0
	echo -e "  online version: $GREEN$online_version$STD \\n"
}

script_upgrade(){		# 01/06/2018

	if [ ! -w "$dirscript/$script" ]; then
		[ "$EUID" -ne 0 ] && f__die "fatal error: the upgrade must be made in root"
	fi
	! curl --silent --show-error -o "/tmp/$script" "$url_script" && f__die "error loading script (curl $?)"
	if grep -q '^### END CONTROL' "/tmp/$script"; then 
		script_get_version "$( < "/tmp/$script" )"
		mv "/tmp/$script" "$dirscript/$script"
		chmod 775 "$dirscript/$script"
	else
		f__die "failure update, incomplete download"
	fi
	rm "/tmp/$script" 2>/dev/null
	echo
}

usage(){		# 03/06/2018

	cat <<- end
	  usage:  ${BLUE}$script [options]${STD}        ( ${RED}options and arguments must be SEPARATED by one space$STRD )

	${BLUE}    -4, -6, -46   ${STD}: protocols to use: ipv4, ipv6, ipv4 & ipv6. by default, the protocol(s) used in the net layer 
	${BLUE}        --bench   ${STD}: run with all lists of domains to test
	${BLUE}        --dev     ${STD}: use dev branch for update or for version number
	${BLUE}        --drill   ${STD}: drill is forced if existing, otherwise dig has priority 
	${BLUE}    -e, --export  ${STD}: export on a pastebin, the file ${script}_report.md created for that
	${BLUE}    -c, --compress${STD}: no extended report, only time averages
	${BLUE}    -d, --domains ${STD}: choice between 3 test domain lists: base (defaut), alt, atld, or easy 
	${BLUE}    -f, --file    ${STD}: the ip in <file> are tested, replace /etc/resolv.conf. format: ip[ # name] per line
	${BLUE}        --nodns   ${STD}: only the nameservers in /etc/resolv.conf or in <file> are tested, no other dns servers used 
	${BLUE}        --noresolv${STD}: the file /etc/resolv.conf is not read, implied with --file
	${BLUE}        --nosort  ${STD}: no sorted report on average column
	${BLUE}        --opt     ${STD}: print list of dns servers and domains used for tests
	${BLUE}    -h, --help    ${STD}: this help
	${BLUE}    -s, --sort    ${STD}: sort on domain number
	${BLUE}    -u, --upgrade ${STD}: load and replace the script in place
	${BLUE}    -v, --version ${STD}: version of the script online and in place

	  examples:
	${BLUE}      ./ntest                    ${STD}: full report, with nameservers in /etc/resolv.conf and few open DNS servers
	${BLUE}      ./ntest --nodns --compress ${STD}: report with only averages with only nameservers in /etc/resolv.conf
	${BLUE}      ./ntest -e  --noresolv     ${STD}: export on a pastebin, to exchange a test
	${BLUE}      ./ntest --noresolv -d easy ${STD}: full report, with domains to test easy, performances are better (responses in cache DNS)
	${BLUE}      ./ntest -h  -d alt         ${STD}: this help, with domain list alt(ernative)
	${BLUE}      ./ntest --opt              ${STD}: displays all parameters
	${BLUE}      ./ntest --sort 5           ${STD}: sort on domain number 5
	${BLUE}      ./ntest --bench --noresolv ${STD}: bench for all open DNS, protocols configured in the net layer 
	${BLUE}      ./ntest --bench --nodns    ${STD}: bench for names's servers in resolv.conf, protocols configured in the net layer 

	  more info: ${GREEN}$url_notice${STD}

	end
}

# shellcheck disable=SC1117
usage_version(){		# 01/06/2018

	if type -p tput &>/dev/null && tput setaf 1 &>/dev/null; then
		  GREEN=$( tput setaf 2 )		# ok
		   BLUE=$( tput setaf 4 )		# info
			RED=$( tput setaf 1 )		# alerte
			STD=$( tput sgr0 )			# retour "normal"
	else 
		 GREEN=$'\033[0;32m'		# ok
		  BLUE=$'\033[0;34m'		# info
		   RED=$'\033[0;31m'		# alerte
		   STD=$'\033[0m'			# standard
	fi

	cat <<- end
	             _            _   
	   _ __  ___| |_ ___  ___| |_ 
	  | '_ \/ __| __/ _ \/ __| __|
	  | | | \__ \ ||  __/\__ \ |_ 
	  |_| |_|___/\__\___||___/\__| $script_options
	        version: $GREEN$version $date$STD
	
	end
}

	# [$1=protocol used]
z_core(){		# 03/06/2018
	local ns server_ip server_name width wcol margin typeIp header xyz domain line time_sum counter counterNotFound notfound 
	local time time_sum average unit report footer output ligneRapport 

	if [ "$drilltest" ] && command -v drill > /dev/null; then
		dig=drill
	fi

		# first column width 
	for ns in "${nameservers[@]}" "${dns[@]}"; do
		server_ip=${ns%[[:blank:]]#*}
		server_name=${ns#*#[[:blank:]]}
		[[ "$server_name" =~ \# ]] && server_name=${ns#*#}
		(( ( ${#server_ip} + ${#server_name} + 4 ) >= width )) && width=$(( ${#server_ip} + ${#server_name} + 4 ))
	done

	wcol=8
	margin="  "
	[ "$1" ] && typeIp="IPV${1#-}"
		# report header
	header=$( printf "${RED}${margin}%10s%-$((width-10))s$STD" "$typeIp" )
	if [ -z "$compress" ]; then
		xyz=1
		for domain in "${domains_test[@]}"; do
			header+=$( printf "%-${wcol}s" "$xyz:${domain#*.}" )
			(( xyz++ ))
		done
	fi
	header+=$( printf "%$(( wcol + 3 ))s\\n" "Average" )
		# report's lines
	for ns in "${nameservers[@]}" "${dns[@]}"; do
		server_ip=${ns%[[:blank:]]#*}
		server_name=${ns#*#[[:blank:]]}
		[[ "$server_name" =~ \# ]] && server_name=${ns#*#}
		printf "\\r  %40s" " "
		printf "\\r  %s " "$server_name"
		line=$( printf "${margin}%-${width}s" "$server_name ($server_ip)" )

		time_sum=0
		counter=0
		counterNotFound=0
		for domain in "${domains_test[@]}"; do
			printf .
			if [ "$dig" == "dig" ]; then
				! time=$( LC_ALL=C $dig +tries=1 +timeout=1 +stats @"$server_ip" "$domain" 2>/dev/null ) && time="n/a"
			elif [ "$dig" == "drill" ]; then
				! time=$( LC_ALL=C drill  @"$server_ip" "$domain" 2>/dev/null ) && time="n/a"
			fi
			if [ "$time" != 'n/a' ] ; then
				[[ "${time,,}" =~ ^.*flags:.*answer:\ 0 ]] && notfound="yes" || notfound=""
				if [[ "${time,,}" =~ ^.*query\ time:\ ([0-9].*)\ msec  ]]; then
					time="${BASH_REMATCH[1]}"
					time_sum=$(( time_sum + time ))
					(( counter++ ))
				fi
				if [ "$notfound" ]; then
					time="-$time"
					(( counterNotFound++ ))
				fi
			fi
			if [ -z "$compress" ]; then
				line+=$( printf "%-${wcol}s" "$time" )
			fi
		done
		if (( counter != 0 )); then
			average=$(( time_sum * 100  / counter ))
			average=${average::-2}.${average:(-2):2}
			unit=" ms"
		else
			average="999999"
			unit=" n/a"
		fi
		if (( counterNotFound == domains_qty )); then
			average="999998"
			unit=" n/a"
		fi
		report+="$line$( printf "%$(( wcol + 1 ))s" "$average" )$unit"$'\n'
	done
	report=${report%$'\n'}
	printf "\\r  %40s\\r" " "

		# sort if no nosort option and command sort
	if [ -z "$nosort" ] && command -v sort > /dev/null; then
		[ "$compress" ] && unset domains_qty 
		if [ "$dtos" ] ; then
			report=$( echo "$report" | sort -n -k $(( dtos + 2 )) )
		else
			report=$( echo "$report" | sort -n -k $(( domains_qty + 3 )) )
		fi
	fi

	echo "$header"
	echo "$report"

	if [[ -z "$compress" ]]; then
		echo -en "\\n  tested domains ('$testsarray' list):\\n  "
		i=1
		for domain in "${domains_test[@]}"; do
			footer+=$( echo -n "$i:${domain}" )" "
			(( i++ ))
		done
		footer+=$'\n'"      n/a indicates an inaccessible server, dash (-) indicates a domain not found "
		echo "$footer"
		echo
	fi

	if [ "$export" ]; then
		output="${script}_report.md"
		ligneRapport="Report $(date '+%d/%m/%Y %H:%M %z')  ◇  $(uname -n)  ◇  $0 $script_options  ◇  $version"
		echo "$ligneRapport" > "$output"
		{
			printf "\\n%s\\n" '```'
			echo "$header"
			echo "$report"
			printf "%s\\n" '```'
			[ "$footer" ] && echo "$footer"
		} >> "$output"
		printf "%s \\n\\n" "report url:"
		curl -s --upload-file "$output" "https://transfer.sh/$output"
		echo
		echo "voir le rapport généré: pager $output"
		echo "effacer le rapport généré: rm $output"
	fi
}

z_options(){		# 02/06/2018
	local width testProto proto nameservers xyz dns ns ip test domain

		# display open dns
	if [ -z "$nodns" ]; then
		case "$protocol" in
			-4 | -6 ) testProto="$protocol" ;;
				*   ) testProto=( -4 -6 ) ;;
		esac
		for proto in "${testProto[@]}"; do
			case "$proto" in
				-4 ) dns=( "${dns4[@]}" ) ;;
				-6 ) dns=( "${dns6[@]}" ) ;;
			esac
				# display dns
			xyz=0
			width=0
			for ns in "${dns[@]}"; do
				(( ${#ns} > width )) && width=$(( ${#ns} + 4 ))
			done
			[ -z "$nodns" ] && echo "  ipv${proto#-}:"
			for ns in "${dns[@]}"; do 
				ip=${ns% #*}
				ns=${ns#*# }
				printf "    %-${width}s" "$ns ( $ip )"
				if (( xyz == 1 ));then
					echo
					xyz=0
				else
					(( xyz++ ))
				fi
			done
			echo
			(( ${#dns[@]} % 2 == 1 )) && echo
		done
	fi
		# display resolv.conf or dns file
	if [ -z "$noresolv" ]; then
		case "$protocol" in
			-4 ) nameservers=( "${nameservers4[@]}" ) ;;
			-6 ) nameservers=( "${nameservers6[@]}" ) ;;
			-46 ) nameservers=( "${nameservers4[@]}" "${nameservers6[@]}" ) ;;
		esac
		echo "  $dnsfile:"
		xyz=0
		width=0
		for ns in "${nameservers[@]}"; do
			(( ${#ns} > width )) && width=$(( ${#ns} + 4 ))
		done
		for ns in "${nameservers[@]}"; do
			ip=${ns%[[:blank:]]#*}
			ns=${ns#*#[[:blank:]]}
			[[ "$ns" =~ \# ]] && ns=${ns#*#}
			printf "    %-${width}s" "$ns ( $ip )"
			if (( xyz == 1 ));then
				echo
				xyz=0
			else
				(( xyz++ ))
			fi
		done
		echo
		(( ${#nameservers[@]} % 2 == 1 )) && echo
	fi
		# display test domains
	for test in "${td[@]}"; do
		testsarray="$test"
		assign_variables
		echo "  $test list:"
		xyz=0
		width=0
		for domain in "${domains_test[@]}"; do
			(( ${#domain} > width )) && width=$(( ${#domain} + 4 ))
		done
		printf "    "
		for domain in "${!domains_test[@]}"; do 
			printf "%-${width}s " "${domains_test[$domain]}"
			if (( xyz == 4 ));then
				echo
				xyz=0
				(( domain+1  != ${#domains_test[@]} )) && printf "    "
			else
				(( xyz++ ))
			fi
		done
		(( ${#domains_test[@]} % 5 != 0 )) && echo 
	done
	echo
}

#######  variables  script -----------------------------------------------------

url_script="https://framagit.org/sdeb/nstest/raw/master/nstest"
url_notice="https://framaclic.org/h/doc-nstest"		# https://framagit.org/sdeb/nstest/blob/master/README.md

#######  options processing ----------------------------------------------------

f__basedirname
script_options="$*"
usage_version
testsarray="base"
totest="$testsarray"
td=( base alt easy atld )

	# options
while (( $# )) ; do
	case "$1" in
		-4 | -6 | -46 | -64  ) protocol="$1"  ;;
			 --bench    ) totest=( "${td[@]}" ) ; bench='yes' ;;
			 --dev      ) url_script=${url_script//\/master\///dev/} ;;
			 --drill    ) drilltest='yes'  ;;
		-e | --export   ) export='yes'     ;;
		-c | --compress ) compress='yes'   ;;
		-d | --domains  ) testsarray="$2" ; shift
			case "$testsarray" in 
				alt | atld | base | easy) ;; 
				* ) echo '  test domains: base selected'; testsarray="base" ;;
			esac ;;
		-f | --file     ) dnsfile="$2" ; shift ;;
			 --nodns    ) nodns='yes'      ;;
			 --noresolv ) noresolv='yes'   ;;
			 --nosort   ) nosort='yes'     ;;
		-s | --sort     ) dtos="$2" ; shift ;;
		* ) options+=( "$1" )
	esac
	shift
done

readingFileNs "$dnsfile"
assign_variables

case "$protocol" in
	-4 | -6 | -46 ) ;;
	-64 ) protocol="-46" ;;
	  * ) protocol=$( f_ip_proto_detect ) ;; 
esac
case "$protocol" in
	-4  ) dns=( "${dns4[@]}" )
		  nameservers=( "${nameservers4[@]}" ) ;;
	-6  ) dns=( "${dns6[@]}" )
		  nameservers=( "${nameservers6[@]}" ) ;;
	-46 ) dns=( "${dns4[@]}" "${dns6[@]}" )
		  nameservers=( "${nameservers4[@]}" "${nameservers6[@]}" ) ;;
esac

[ "$nodns" ] && unset dns
[ "$noresolv" ] && unset nameservers
[[ -z "$noresolv" && -z "$dnsfile" ]] && dnsfile="resolv.conf"

	# actions
for i in "${options[@]}" ; do
	case "$i" in
		     --opt      ) z_options ; exit ;;
		-u | --upgrade  )   script_upgrade   ; exit ;;
		-v | --version  )   script_get_version; exit ;;
		-h | --help | * ) usage ; exit ;;
	esac
done


####  nstest core --------------------------------------------------------------

if [[ "$nodns" && "$noresolv" ]]; then
	echo -e "$RED  nothing to do \\n$STD"
	exit
fi

for list in "${!totest[@]}"; do
	testsarray="${totest[$list]}"
	getTime
	if [[ $bench ]]; then
		case "$protocol" in
			-4  ) protos=-4 ;;
			-6  ) protos=-6 ;;
			-46 ) protos=( -4 -6 ) ;;
		esac
		for proto in "${protos[@]}"; do
			case "$proto" in
				-4 ) dns=( "${dns4[@]}" )
					 nameservers=( "${nameservers4[@]}" ) ;;
				-6 ) dns=( "${dns6[@]}" )
					 nameservers=( "${nameservers6[@]}" ) ;;
			esac
			[ "$nodns" ] && unset dns
			[ "$noresolv" ] && unset nameservers
			z_core "$proto"
			echo -n "  execution time: "
			echo -en "$BLUE$( getTime end:auto )$STD\\t ($( date '+%d/%m/%Y %H:%M %z' ))\\n"
			echo
		done
		(( list != ${#totest[@]}-1 )) && sleep 30s
	else
		z_core
		echo -n "  execution time: "
		echo -en "$BLUE$( getTime end:auto )$STD\\t ($( date '+%d/%m/%Y %H:%M %z' ))\\n"
		echo
	fi
done

exit 0
### END CONTROL (download control)

curl -OL https://framaclic.org/h/nstest
wget -nv -O nstest https://framaclic.org/h/nstest
chmod +x nstest && ./nstest

https://framagit.org/sdeb/nstest/raw/master/nstest
